### ISSUE TITLE
WebKitGTK Support?

### ISSUE THREAD

**Issue by tokyovigilante** [AparokshaUI/adwaita-swift#18]
### Describe the solution you'd like

It would be awesome if GTK WebKit views were supported, to enable embedded web content or even full web-browers in Swift.

### Describe alternatives you've considered

Using the GTK or WPE WebKit APIs from Swift can be done, but there is some significant boilerplate required to generate windows and integrate with OpenGL etc in the case of WPE

### Additional context

Thanks!

**Comment by david-swift** [comment]
WebKitGTK [is a separate library](https://webkitgtk.org/reference/webkit2gtk/stable/index.html), so I would not include it in the core package, but create a new package, similar to the one for [GtkSourceView](https://github.com/AparokshaUI/CodeEditor). Thanks for the suggestion , I‘ll definitely create this package at some point!

**Comment by tokyovigilante** [comment]
Awesome, thanks for pointing me to the `GtkSourceView`, package, I was able to just replace the references and get a `GtkWebView` up and running with `adwaita-swift`.
