### ISSUE TITLE
Description of the feature request

### ISSUE THREAD

**Issue by lesclaz** [AparokshaUI/adwaita-swift#24]
### Is your feature request related to a problem? Please describe.

Currently, the Picture().data(data) function does not accept a Binding<Data?> as a parameter for Data, which limits the reactivity of the UI in situations where users need to request a new captcha.

### Describe the solution you'd like

I suggest modifying the Picture().data(data) function to accept a Binding<Data?> instead of direct Data?. This would allow the captcha image to be handled in a similar manner to other visual components like Text and Button, using State to update the UI reactively.

### Describe alternatives you've considered

.

### Additional context

I am developing a login view that includes a captcha to increase security. The service requires users to complete the captcha, but since it is common for users to have difficulty understanding the content of the captcha image, it is essential to allow them to request a new image.

**Comment by david-swift** [comment]
I tried to explain [`State`](https://aparokshaui.github.io/adwaita-swift/documentation/adwaita/state) and [`Binding`](https://aparokshaui.github.io/adwaita-swift/documentation/adwaita/binding) [here](https://aparokshaui.github.io/adwaita-swift/documentation/adwaita/creatingviews#State). What `Binding` enables is to be able to modify data from within a child view of the view storing the data. Making the image data binding would mean that the `Picture` view itself would be able to modify the image data, which is not the case. It can display an image only. Therefore, it's possible to display a new image without requiring a binding in the data modifier of `Picture`.

```swift
import Adwaita

struct PictureDemo: View {

    @State private var image = Captcha.randomImage()
    var app: GTUIApp
    var window: GTUIWindow

    var view: Body {
        Picture()
            .data(image.data)
        Button("Request New Image") {
            data = Captcha.randomImage()
        }
        .halign(.center)
        .style("pill")
        .style("suggested-action")
        .padding()
    }

}
```

You can see that the line `data = Captcha.randomImageData()` modifies the `data` state variable. This automatically updates the UI, including `Picture().data(data)`.

**Comment by lesclaz** [comment]
Thank you very much. I don't know why, but earlier when I tried it didn't work, surely I hadn't done something right.
