### ISSUE TITLE
Xcode adwaita.h not found

### ISSUE THREAD

**Issue by kobutri** [AparokshaUI/adwaita-swift#32]
### Describe the bug

If I try to build the project in the template repository via Xcode I get the build error in shim.h that `#include <adwaita.h>` doesn't work because it can't find `adwaita.h`.
It works just fine with with `swift build`/`swift run` from the terminal.

### To Reproduce

1. install Xcode via the AppStore
2. install Adwaita via `brew install libadwaita`
3. clone the template repository
4. open it in xcode
5. click the run button in Xcode

### Expected behavior

project should build and open

### Additional context

MacOS 14.5
Xcode 15.4

**Comment by david-swift** [comment]
Unfortunately, I'm not able to reproduce this with the same setup (except I installed Xcode via [Xcodes](https://github.com/XcodesOrg/XcodesApp) and am currently on version 15.3). Another, maybe somehow related issue appeared to me as well (https://github.com/AparokshaUI/adwaita-swift/issues/11). Maybe you could try following the solution to this problem: https://github.com/AparokshaUI/adwaita-swift/issues/11#issuecomment-2026804538?

I want to stress that this library works best on Linux, using the GNOME Builder IDE and Flatpak. More information on how to set up a comfortable developer environment can be found [here](https://aparokshaui.github.io/adwaita-swift/tutorials/adwaita/setupgnome), or you could also set it up in a VM.

I'll upgrade to Xcode 15.4 to see whether a bug was introduced in the new version.

**Comment by iDevPro** [comment]
> Unfortunately, I'm not able to reproduce this with the same setup (except I installed Xcode via [Xcodes](https://github.com/XcodesOrg/XcodesApp) and am currently on version 15.3). Another, maybe somehow related issue appeared to me as well (#11). Maybe you could try following the solution to this problem: [#11 (comment)](https://github.com/AparokshaUI/adwaita-swift/issues/11#issuecomment-2026804538)?
> 
> I want to stress that this library works best on Linux, using the GNOME Builder IDE and Flatpak. More information on how to set up a comfortable developer environment can be found [here](https://aparokshaui.github.io/adwaita-swift/tutorials/adwaita/setupgnome), or you could also set it up in a VM.
> 
> I'll upgrade to Xcode 15.4 to see whether a bug was introduced in the new version.

I have installed gtk4 and adwaita but:
'adwaita.h' file not found
... in Xcode 15.4  :)

**Comment by iDevPro** [comment]
> Unfortunately, I'm not able to reproduce this with the same setup (except I installed Xcode via [Xcodes](https://github.com/XcodesOrg/XcodesApp) and am currently on version 15.3). Another, maybe somehow related issue appeared to me as well (#11). Maybe you could try following the solution to this problem: [#11 (comment)](https://github.com/AparokshaUI/adwaita-swift/issues/11#issuecomment-2026804538)?
> 
> I want to stress that this library works best on Linux, using the GNOME Builder IDE and Flatpak. More information on how to set up a comfortable developer environment can be found [here](https://aparokshaui.github.io/adwaita-swift/tutorials/adwaita/setupgnome), or you could also set it up in a VM.
> 
> I'll upgrade to Xcode 15.4 to see whether a bug was introduced in the new version.

I have problem with tutorial with localizable programm, when remove localization and yaml convertation all build success :)

**Comment by david-swift** [comment]
> I have problem with tutorial with localizable programm, when remove localization and yaml convertation all build success :)

Did you also get the `adwaita.h` error, @iDevPro? This would be very strange as the Localizable package does not depend on Libadwaita, but the adwaita-swift package does.

**Comment by david-swift** [comment]
@iDevPro I also experienced a problem with the Localizable package after updating to Xcode 16 Beta. I could solve it by simply running `swift run` in the terminal (which succeeded), and from then on it worked in Xcode as well. Could you try this, @iDevPro? This doesn't seem to be the case for @kobutri's `adwaita.h` problem as far as I understand?

**Comment by david-swift** [comment]
This issue has moved to https://git.aparoksha.dev/aparoksha/adwaita-swift/issues/32
