### ISSUE TITLE
CAdw build failed

### ISSUE THREAD

**Issue by iDevPro** [AparokshaUI/adwaita-swift#42]
### Describe the bug

<img width="803" alt="Снимок экрана 2024-07-13 в 10 56 30" src="https://github.com/user-attachments/assets/a5529272-f8ae-4a00-a718-a18aae938b05">

<img width="743" alt="Снимок экрана 2024-07-13 в 10 57 09" src="https://github.com/user-attachments/assets/fe7bb461-8558-460f-a850-f9c3fcd79e81">

<img width="685" alt="Снимок экрана 2024-07-13 в 10 57 27" src="https://github.com/user-attachments/assets/2770a9c2-9d07-4f04-b19c-05d975aa77d4">

### To Reproduce

1. Create project with Adwaita
2. run in xcode
3. that's all

### Expected behavior

Run project in xcode not only swift run :)

**Comment by david-swift** [comment]
Thanks for opening the issue! This is a known problem. See #21 for instructions on how to fix it. Let me know whether it works for you!

**Comment by iDevPro** [comment]
> Thanks for opening the issue! This is a known problem. See #21 for instructions on how to fix it. Let me know whether it works for you!

This workaround works for me too :) THX, I suppose that issue between SDK from Xcode and Adwaita from Homebrew :)

**Comment by david-swift** [comment]
Thanks for opening your series of issues and helping improving the Adwaita for Swift framework! I will close this issue as completed.
