### ISSUE TITLE
Flatpak VSCode: no such module 'Adwaita'

### ISSUE THREAD

**Issue by kdwk** [AparokshaUI/adwaita-swift#50]
### Describe the bug

When developing Adwaita Swift apps in VSCode, `import Adwaita` is flagged as an error with `No such module 'Adwaita'`, and code docs and autocomplete don't work. However, when using flatpak-builder to run the app it compiles and runs successfully.

### To Reproduce

1. Clone the template repository
2. Open in VSCode (Flatpak)
3. Any `import Adwaita` statements are flagged as errors

### Expected behavior

Adwaita is imported correctly and code docs and autocomplete work correctly

### Additional context

1. Already installed Swift SDK extension from Flathub
2. Already set FLATPAK_ENABLE_SDK_EXT=*
3.    ` dependencies: [
        .package(url: "https://github.com/AparokshaUI/Adwaita", from: "0.2.0")
    ]` is already added to Package.swift
4. Code docs and autocomplete for other Swift code, including standard library functions, work

**Comment by david-swift** [comment]
This issue has moved to https://git.aparoksha.dev/aparoksha/adwaita-swift/issues/50
