### ISSUE TITLE
Specify required version of libadwaita

### ISSUE THREAD

**Issue by vpzomtrrfrt** [AparokshaUI/adwaita-swift#52]
### Is your feature request related to a problem? Please describe.

Trying to compile a project using this library

### Describe the solution you'd like

The README should mention the required version of libadwaita. Ideally the library should also check this and give a better error message.

#25 mentions that 1.5 is required, is that still the case?

### Describe alternatives you've considered

installing every version of libadwaita until it works

### Additional context

Requiring 1.5 is also unfortunate since I don't think any of the swift Docker images use a distro version that packages it

**Comment by david-swift** [comment]
Thanks for the request! I'll add the version to the README and will make the program crash based on [this information](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/const.MINOR_VERSION.html) in the libadwaita package.

The current version required is **1.5** (or later), but I'll update to 1.6 soon. Here are the different ways you could install/access libadwaita:

- Flatpak (recommended way). Take a look at the [template](https://github.com/AparokshaUI/AdwaitaTemplate) and build using GNOME Builder, the Flatpak extension for VS Code, or the Flatpak Builder command line tool. This is the easiest way IMO and a very solid way of publishing, so one will probably set up Flatpak at some point anyways.
- Homebrew. I will update only to the latest version as soon as it is available on Homebrew (which is extremely fast in upgrading). So you could install Homebrew on your Linux or macOS system and let it manage libadwaita.
- In some cases, obviously, the system's package manager, but yeah, this won't work on some systems (not recommended).

**Comment by david-swift** [comment]
This issue has moved to https://git.aparoksha.dev/aparoksha/adwaita-swift/issues/52
