### ISSUE TITLE
Getting green ticks on the SPI build matrix

### ISSUE THREAD

**Issue by finestructure** [AparokshaUI/adwaita-swift#6]
Hi, it's great to see this package on swift.org but I noticed that we're currently showing all grey boxes over on the [SPI compatibility matrix](https://swiftpackageindex.com/AparokshaUI/adwaita-swift):

![CleanShot 2024-03-26 at 11 17 21@2x](https://github.com/AparokshaUI/adwaita-swift/assets/65520/8c7810d6-0f7e-4e07-a944-b9d7f0d8ed18)

We currently don't support adding OS level dependencies for build on Apple platforms but our Linux builders are a bit more flexible. I've tried running a build locally with the dependencies set up but I'm getting build errors:

```
/host/adwaita-swift/Sources/Adwaita/Model/User Interface/Window/GTUIAboutWindow.swift:18:23: error: cannot find 'adw_about_window_new_from_appdata' in scope
            pointer = adw_about_window_new_from_appdata(filePath, nil)?.cast()
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/host/adwaita-swift/Sources/Adwaita/Model/User Interface/Window/GTUIAboutWindow.swift:18:67: error: 'nil' requires a contextual type
            pointer = adw_about_window_new_from_appdata(filePath, nil)?.cast()
                                                                  ^
```

Here are the steps to reproduce:

```
docker run --rm -it -v $PWD:/host -w /host --network="host" --entrypoint bash swift:5.10-jammy
apt-get update
apt-get install libadwaita-1-dev
git clone https://github.com/AparokshaUI/adwaita-swift
cd adwaita-swift
swift build
```

It looks like `libadwaita-1-dev` isn't the correct dependency. Do you know what dev package needs to be installed on Ubuntu?

**Comment by david-swift** [comment]
Thanks for looking into this!

I think is is `libadwaita-1-dev`, but probably, the Ubuntu version is not yet on the latest version? This package requires Libadwaita 1.5 (it is normally used inside a Flatpak, and Homebrew is already on version 1.5). The latest version seems to be [Beta on Ubuntu packages](https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libadwaita-1-dev&searchon=names).

**Comment by finestructure** [comment]
Oh, I see, thanks for checking that. Is there a way to get the beta package on jammy?

The alternative would be to use a `noble` base image but there [isn't one yet with Swift](https://hub.docker.com/_/swift/tags?page=1&name=noble) on it, so it'd be a whole different thing to get that set up 😕

**Comment by david-swift** [comment]
@finestructure I'd like to move to DocC for the documentation and host it on the SPI, since I like to have the "Reference documentation" and articles/tutorials combined in one service, and as SPI offers that amazing, super simple approach to hosting it. I wanted to ask whether, as soon as we can fix the compatibility matrix problem, we can apply the same solution to the documentation generator? I don't know whether that is a good approach, but Homebrew is very fast with updating to the newest versions of libadwaita (I also won't update this package faster than Homebrew). Maybe we can install via Homebrew?

**Comment by david-swift** [comment]
@finestructure does it have to be Ubuntu? With e.g. Fedora 40 it's very simple (the Swift version is 5.8.1):
```
sudo docker run --rm -it -v $PWD:/host -w /host --network="host" --entrypoint bash fedora:40
dnf install swiftlang -y
dnf install libadwaita-devel -y
dnf install git -y
git clone https://github.com/AparokshaUI/adwaita-swift
cd adwaita-swift
swift build
```

**Comment by finestructure** [comment]
> @finestructure I'd like to move to DocC for the documentation and host it on the SPI, since I like to have the "Reference documentation" and articles/tutorials combined in one service, and as SPI offers that amazing, super simple approach to hosting it. I wanted to ask whether, as soon as we can fix the compatibility matrix problem, we can apply the same solution to the documentation generator? I don't know whether that is a good approach, but Homebrew is very fast with updating to the newest versions of libadwaita (I also won't update this package faster than Homebrew). Maybe we can install via Homebrew?

The doc generation runs as an additional phase right after building, so once builds work, doc gen is pretty much automatic.

We don't currently support installing dependencies with Homebrew but we may have that in place in a few weeks, if things go as planned.

The route with a linux base image is currently probably our best shot to get this working (and we support doc gen on Linux as well).

**Comment by finestructure** [comment]
> @finestructure does it have to be Ubuntu? With e.g. Fedora 40 it's very simple (the Swift version is 5.8.1):
> 
> ```
> 
> sudo docker run --rm -it -v $PWD:/host -w /host --network="host" --entrypoint bash fedora:40
> 
> dnf install swiftlang -y
> 
> dnf install libadwaita-devel -y
> 
> dnf install git -y
> 
> git clone https://github.com/AparokshaUI/adwaita-swift
> 
> cd adwaita-swift
> 
> swift build
> 
> ```

That would work in principle, yes, though it'd be a bit more complicated to set up than just extending our existing [Linux base images](https://gitlab.com/finestructure/spi-images/).

Are there other Swift versions available on Fedora? As you can see from the linked repo we try to create base images for all supported Swift versions (5.7, 5.8, 5.9, 5.10), so it'd be good if that was possible.

**Comment by david-swift** [comment]
@finestructure The downloads on the Swift website are probably the easiest way for using a specific version:
```
sudo docker run --rm -it -v $PWD:/host -w /host --network="host" --entrypoint bash fedora:40

curl https://download.swift.org/swift-5.10-release/amazonlinux2/swift-5.10-RELEASE/swift-5.10-RELEASE-amazonlinux2.tar.gz --output swift.tar.gz
tar -xvzf swift.tar.gz

dnf install libadwaita-devel -y

dnf install git -y
git clone https://github.com/AparokshaUI/adwaita-swift
cd adwaita-swift
../swift-*.**-RELEASE-amazonlinux2/usr/bin/swift build
```

**Comment by finestructure** [comment]
Ok, great, this seems to work. I've set up a [new base image](https://gitlab.com/finestructure/spi-images/-/merge_requests/24) and will re-trigger builds once it's done generating the images.

**Comment by finestructure** [comment]
Well, actually it'll require a `.spi.yml` change, PR open.

**Comment by finestructure** [comment]
Builds retriggered and passing now:

![CleanShot 2024-04-02 at 14 22 57@2x](https://github.com/AparokshaUI/adwaita-swift/assets/65520/0c8d80e1-0989-44c4-89b9-fd3d6e38d582)

BTW, note that the documentation link is broken. I believe it's because the ref in `.spi.yml` isn't a proper https link:

```
  documentation: "aparokshaui.github.io/adwaita-swift/"
```

(This should be fixed if you switch over the doc hosting as discussed.)

**Comment by finestructure** [comment]
I think it should, see https://swiftpackageindex.com/SwiftPackageIndex/SPIManifest/1.4.1/documentation/spimanifest for details!
